### ISSUE TITLE
Multiple changes in one commit

### ISSUE THREAD

**Issue by tprochazka** [kovmarci86/android-secure-preferences#1]
Code like

``` java
        getPrefs().edit()
            .putString("closureID", closureID)
            .putString("merchantName", merchantName)
            .putString("sourceAuthKey", sourceAuthKey)
            .commit();

```

doesn't work, because you return unsecured (standard) Editor from putXY methods instead of SecuredEditor.

**Comment by kovmarci86** [comment]
Hi,
I'll raise a bug.
feel free to fix it and create a pull request / or i will fix it in the
next days.
Best regards,
Marcell
2013.06.07. 22:00, "tprochazka" notifications@github.com ezt írta:

**Comment by tprochazka** [comment]
I just started to work on this fix.
I will also add support for new android version and methods like apply() or putStringSet()

**Comment by kovmarci86** [comment]
Merged!
TY,
Marcell
